#!/usr/bin/env python3
"""Generate the Android strings.xml files from the iOS Localizable.strings.

The 27 captions and every other string come straight from the iOS app, so the
two apps never drift. Only two strings get Android wording (see OVERRIDES).

    python3 android/tool/import_strings.py
"""
import pathlib
import re
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[2]
RES = ROOT / "android" / "app" / "src" / "main" / "res"
LANGS = {"en": "values", "zh-Hans": "values-zh-rCN", "ja": "values-ja"}
OVERRIDES = {
    "en": {
        "tip_body": "Meow is free and lives on ads. Treat the author, or the author's cat, "
                    "and the ads are gone for good on every device with your Google account.",
        "tip_unavailable": "Can't reach Google Play right now. Try again later.",
    },
    "zh-Hans": {
        "tip_body": "猫叫模拟器免费，靠广告养着。请作者喝杯咖啡，或者给作者家的猫买个罐罐，"
                    "广告就永久消失，同一 Google 账号的所有设备都适用。",
        "tip_unavailable": "现在连不上 Google Play，请稍后再试。",
    },
    "ja": {
        "tip_body": "ニャーは無料で、広告で成り立っています。作者にコーヒーをおごるか、"
                    "作者の猫に缶詰をおごると、広告が永久に消えます。同じ Google アカウントのすべての端末で有効です。",
        "tip_unavailable": "Google Play に接続できません。あとでもう一度お試しください。",
    },
}
PATTERN = re.compile(r'^"([A-Za-z0-9_]+)"\s*=\s*"(.*)";\s*$', re.M)


def read_strings(lproj):
    text = (ROOT / "meow" / f"{lproj}.lproj" / "Localizable.strings").read_text(encoding="utf-8")
    return dict(PATTERN.findall(text))


def to_android(value):
    value = value.replace('\\"', '"').replace("%@", "%1$s")
    value = escape(value)
    return value.replace("'", "\\'").replace('"', '\\"')


def render(strings):
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by android/tool/import_strings.py from meow/*.lproj/Localizable.strings. Do not edit. -->",
        "<resources>",
        f'    <string name="app_name">{to_android(strings["title"])}</string>',
    ]
    for key, value in strings.items():
        lines.append(f'    <string name="{key}">{to_android(value)}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def build(lproj):
    strings = read_strings(lproj)
    strings.update(OVERRIDES[lproj])
    return render(strings)


def main():
    for lproj, folder in LANGS.items():
        out = RES / folder / "strings.xml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(build(lproj), encoding="utf-8")
        print(out.relative_to(ROOT))


if __name__ == "__main__":
    main()
